title: Daniel @ Dantas Files
# show_excerpts: true
paginate: 20
description: "Technology in NJ. Ph.D from ğŸ¯Princeton Computer Science. B.S. from ğŸ»Cornell Computer Science"
future: true
author:
  name: Daniel Dantas
  email: daniel@dantasfiles.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  
remote_theme: jekyll/minima




minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/dantasfiles" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/dantasfiles" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=kGsoFNQAAAAJ" }
    - { platform: x,              user_url: "https://x.com/dantasfiles" }
  social_links:
    - icon: github
      url: "https://github.com/dantasfiles"
  #  - title: Jekyll at X (formerly Twitter)
  #    icon: x-twitter
  #    url: "https://x.com/jekyllrb"

