title: Daniel Dantas (@dantasfiles)
show_excerpts: true
paginate: 20
description: "I enjoy exploring, diagnosing & transforming large, complex software projects. Ph.D from ğŸ¯Princeton Computer Science. B.S. from ğŸ»Cornell Computer Science"

remote_theme: jekyll/minima

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/dantasfiles" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/dantasfiles" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=kGsoFNQAAAAJ" }
    - { platform: x,              user_url: "https://x.com/dantasfiles" }

