title: Daniel @ Dantas Files
paginate: 20
description: "Technology in NJ"
future: true
author:
  name: Daniel Dantas
  email: daniel@dantasfiles.com
  url: https://dantasfiles.com/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  
remote_theme: jekyll/minima

show_excerpts: true


minima:
  social_links:
    - icon: github
      url: "https://github.com/dantasfiles"
    - icon: x-twitter
      url: "https://x.com/dantasfiles"
    - icon: google-scholar
      url: "https://scholar.google.com/citations?user=kGsoFNQAAAAJ"
    - icon: linkedin
      url: "https://www.linkedin.com/in/dantasfiles"
    - icon: letterboxd
      url: "https://letterboxd.com/dantasfiles/"
      

