title: Daniel @ Dantas Files
# show_excerpts: true
paginate: 20
description: "Technology in NJ. Ph.D from ğŸ¯Princeton Computer Science. B.S. from ğŸ»Cornell Computer Science"
future: true
author:
  name: Daniel Dantas
  email: daniel@dantasfiles.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  
remote_theme: jekyll/minima




minima:
  social_links:
    - icon: github
      url: "https://github.com/dantasfiles"
    - icon: x-twitter
      url: "https://x.com/dantasfiles"
    - icon: google-scholar
      url: "https://scholar.google.com/citations?user=kGsoFNQAAAAJ"
    - icon: linkedin
      url: "https://www.linkedin.com/in/dantasfiles"
      

